package com.github.ppotseluev.algorate.tools.strategy

import com.github.ppotseluev.algorate.Money
import com.github.ppotseluev.algorate.broker.Broker.CandleResolution.OneMinute
import com.github.ppotseluev.algorate.broker.Broker.CandlesInterval
import com.github.ppotseluev.algorate.broker.Broker.DaysInterval
import com.github.ppotseluev.algorate.strategy.Strategies
import com.github.ppotseluev.algorate.trader.policy.Policy.Decision
import com.github.ppotseluev.algorate.trader.policy.{MoneyManagementPolicy, Policy}

import java.time.LocalDate
//import scala.util.Random

private[strategy] object TestSetup {

  val interval = CandlesInterval(
    interval = DaysInterval(
//      LocalDate.of(2020, 1, 1),
//      LocalDate.of(2022, 7, 20)

//      LocalDate.of(2020, 1, 1),
//      LocalDate.of(2021, 1, 1)
      LocalDate.of(2022, 1, 1),
      LocalDate.of(2022, 12, 31)
    ),
    resolution = OneMinute
  )

  val strategy = Strategies.intraChannel

  def fixedTradeCostPolicy(
      usdTrade: Int = 50,
      rubTrade: Int = 4000
  ): Policy = {
    val money: Money = Map("usd" -> Int.MaxValue, "rub" -> Int.MaxValue)
    new MoneyManagementPolicy(() => Some(money))(
      maxPercentage = 1,
      maxAbsolute = Map(
        "usd" -> usdTrade,
        "rub" -> rubTrade
      )
    )
  } //andThen(_.allowedOrElse(Decision.Allowed(1)))

  private val sampleSize = 30

  private val allTickers = List( //actually not all...
    "OKE",
    "MCD",
    "MET",
    "STX",
    "DFS",
    "TTD",
    "CME",
    "IRBT",
    "ED",
    "MAS",
    "COIN",
    "BRK.B",
    "VZ",
    "TTWO",
    "CRTX",
    "WMT",
    "ASTR",
    "LOW",
    "TSLA",
    "MSTR",
    "IVZ",
    "YNDX",
    "APA",
    "ZM",
    "RCL",
    "BAC",
    "OVV",
    "AMAT",
    "EHTH",
    "DIS",
    "ANAB",
    "AAPL",
    "ROST",
    "CFG",
    "BKNG",
    "EXPE",
    "NEE",
    "MAR",
    "OXY",
    "SCHW",
    "MDT",
    "PFGC",
    "NFLX",
    "EVH",
    "INTC",
    "MOS",
    "INCY",
    "SRPT",
    "KHC",
    "CLOV",
    "TRIP",
    "GD",
    "DVN",
    "MTCH",
    "ETRN",
    "PG",
    "SMAR",
    "META",
    "WDC",
    "CHX",
    "PAGS",
    "HLT",
    "GPS",
    "RACE",
    "GILD",
    "CLF",
    "PINS",
    "ARWR",
    "MGNT",
    "ACAD",
    "M",
    "CNC",
    "GTHX",
    "IDXX",
    "CPRI",
    "ROKU",
    "ORCL",
    "SPR",
    "CHEF",
    "PPC",
    "F",
    "LKOH",
    "GLW",
    "PLZL",
    "MDLZ",
    "FSLY",
    "LHX",
    "CTXS",
    "ABBV",
    "SQ",
    "AMGN",
    "WYNN",
    "EA",
    "UNH",
    "PPL",
    "LVS",
    "EBAY",
    "RL",
    "NVAX",
    "H",
    "PHOR",
    "HA",
    "ETSY",
    "DXC",
    "HEAR",
    "JPM",
    "PBI",
    "HD",
    "MED",
    "NET",
    "SWN",
    "CNK",
    "MO",
    "W",
    "SNAP",
    "PBF",
    "RRC",
    "TSN",
    "BKR",
    "AA",
    "KMI",
    "COTY",
    "BALL",
    "PSX",
    "REGI",
    "HPQ",
    "KO",
    "PM",
    "RRGB",
    "EQT",
    "UBER",
    "COP",
    "GRMN",
    "RKLB",
    "WM",
    "QCOM",
    "ILMN",
    "MDB",
    "WRK",
    "BJRI",
    "TWLO",
    "TXN",
    "UAL",
    "MPC",
    "SPGI",
    "PLTR",
    "HOG",
    "AXP",
    "PRU",
    "BEN",
    "TDOC",
    "TMUS",
    "GS",
    "MA",
    "AIG",
    "OMC",
    "TER",
    "SBUX",
    "BANE",
    "CAT",
    "PYPL",
    "CVS",
    "HCA",
    "UPS",
    "WFC",
    "FDX",
    "SIG",
    "HIG",
    "RIOT",
    "CHGG",
    "YUM",
    "MS",
    "NDAQ",
    "SEDG",
    "GMKN",
    "HPE",
    "Z",
    "SPCE",
    "SPOT",
    "XOM",
    "IOVA",
    "PVH",
    "ALK",
    "SLB",
    "TROW",
    "PARA",
    "WKHS",
    "DAL",
    "MSFT",
    "DHI",
    "ROSN",
    "VRTX",
    "HAS",
    "EIX",
    "SLDB",
    "ALB",
    "KEY",
    "BFH",
    "LYB",
    "DRI",
    "BSX",
    "WMB",
    "PLUG",
    "CHMF",
    "QRVO",
    "HON",
    "LMT",
    "BYND",
    "DOCU",
    "LUV",
    "LEVI",
    "LYFT",
    "CAH",
    "AMD",
    "PUMP",
    "RF",
    "USB",
    "JNJ",
    "KR",
    "TJX",
    "DOW",
    "MNST",
    "NXPI",
    "CMCSA",
    "CCL",
    "UPWK",
    "ADBE",
    "KMB",
    "USFD",
    "ATRA",
    "ZYXI",
    "MU",
    "ATVI",
    "HAL",
    "LRCX",
    "BA",
    "T",
    "REGN",
    "RTX",
    "CVX",
    "AERI",
    "PCG",
    "AYX",
    "GPN",
    "HBAN",
    "V",
    "NVDA",
    "TATN",
    "CLR",
    "WU",
    "ZYNE",
    "MARA",
    "EOG",
    "HRTX",
    "SNPS",
    "NKE",
    "PLAY",
    "MVID",
    "EPAM",
    "ADM",
    "JWN",
    "CRM",
    "TGT",
    "VLO",
    "BMY",
    "PIKK",
    "CNP",
    "OII",
    "TWTR",
    "ABMD",
    "BK",
    "GT",
    "ZS",
    "BIIB",
    "DHR",
    "ADSK",
    "SO",
    "D",
    "XRX",
    "LSRG",
    "SAGE",
    "SYY",
    "UAA",
    "CINF",
    "VREX",
    "HII",
    "NTNX",
    "MRNA",
    "BYSI",
    "CLSK",
    "SIBN",
    "AVGO",
    "CRWD",
    "NEM",
    "EMR",
    "GM",
    "NVTK",
    "MMM",
    "EAR",
    "MTLR",
    "NRG",
    "DDOG",
    "TWOU",
    "FSLR",
    "C",
    "BBY",
    "SAVE",
    "ABT",
    "DXCM",
    "WBA",
    "ACN",
    "PEP",
    "POLY",
    "LLY",
    "ENPH",
    "NTAP",
    "PTON",
    "GOSS",
    "LTHM",
    "CSCO",
    "FCX"
  )

  val ids = List(
    "BBG000BNJHS8",
    "BBG000BRJL00",
    "BBG000BBJQV0",
    "BBG000BBS2Y0",
    "BBG006Q0HY77",
    "BBG00NNG2ZJ8",
    "BBG000BNSZP1",
    "BBG000K4ND22",
    "BBG000BGRY34",
    "BBG006L8G4H1",
    "BBG007TJF1N7",
    "BBG004PYF2N3",
    "BBG0025Y4RY4",
    "BBG000C17X76",
    "BBG000CL9VN6",
    "BBG001M8HHB7",
    "BBG000H8TVT2",
    "BBG000PSKYX7",
    "BBG000BB6KF5",
    "BBG000C3J3C9",
    "BBG000BKFZM4",
    "BBG000D4LWF6",
    "BBG004731354",
    "BBG000GZQ728",
    "BBG000CGC1X8",
    "BBG000R7Z112",
    "BBG000BQQ2S6",
    "BBG000WCFV84",
    "BBG000C5Z1S3",
    "BBG000BCTLF6",
    "BBG000BJF1Z8",
    "BBG000Q3JN03",
    "BBG000BNFLM9",
    "BBG000BWNFZ9",
    "BBG000FDBX90",
    "BBG000BS0ZF1",
    "BBG00475K6C3",
    "BBG002583CV8",
    "BBG000C5HS04",
    "BBG000G0Z878",
    "BBG000BMQPL1"
  )
}
