number of input neurons: 1
number of output neurons: 1
size of population: 100
number of generations: 500
save after each n generations: 10
chance of weight mutation (for each connection): 0.4
dispersion of weight mutation: 0.3
chance of 'goal' connection mutation (for the entire network): 0.05
chance of 'problem' connection mutation (for the entire network): 0.05
chance of neuron duplication (for each neuron): 0.05
chance of neuron deletion (for each neuron): 0.05
chance of delay time mutation (for each neuron): 0
dispersion of delay time: 10
mean delay time: 100
model of neuron (EDC/EC/DC/simple): simple
networks can be recurrent: true
load population from file: false
